# Chemins (Vérifie bien que le dossier SFML est ici)
SFML_I := "C:\Users\fatima ezzahra\Desktop\SFML-2.6.2-windows-gcc-13.1.0-mingw-64-bit\SFML-2.6.2\src\include"
SFML_L := "C:\Users\fatima ezzahra\Desktop\SFML-2.6.2-windows-gcc-13.1.0-mingw-64-bit\SFML-2.6.2\src\lib"

# Options
CXX      := g++
CXXFLAGS := -std=c++17 -I$(SFML_I)
LDFLAGS  := -L$(SFML_L) -lsfml-graphics -lsfml-window -lsfml-audio -lsfml-system

# Cible principale
all:
	$(CXX) *.cpp -o jeu.exe $(CXXFLAGS) $(LDFLAGS)

# Nettoyage
clean:
	del /f *.exe