# Chemins
SFML_INCLUDE := ../src/include
SFML_LIB     := ../src/lib

# Compilateur et options
CXX := g++
CXXFLAGS := -std=c++17 -I$(SFML_INCLUDE)
# AJOUT DE -lsfml-audio ICI
LDFLAGS := -L$(SFML_LIB) -lsfml-graphics -lsfml-window -lsfml-audio -lsfml-system

# Liste des fichiers (AJOUT DE Player.o ICI)
OBJ = main.o Game.o AssetManager.o Menu.o Obstacle.o Player.o
TARGET = SunkentCity.exe

$(TARGET): $(OBJ)
	$(CXX) $(OBJ) -o $(TARGET) $(LDFLAGS)

%.o: %.cpp
	$(CXX) $(CXXFLAGS) -c $< -o $@

clean:
	del *.o $(TARGET)
	clean:
	del /f *.o SunkentCity.exe